# Generated by Django 6.0.2 on 2026-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoo",
            name="title",
            field=models.CharField(),
        ),
    ]
